### ISSUE TITLE
Error since version 1.0.78

### ISSUE THREAD

**Issue by ShlomiD83** [Tikipeter/tikipeter.github.io#127]
Hey,
Unable to get results from Fen Lite since version 1.0.78 came out, running on Windows x64.

2024-09-21 08:34:08.874 T:10212   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'Sources' object has no attribute 'hdr_filter_key'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\ShlomiD\AppData\Roaming\Kodi\addons\plugin.video.fenlight\resources\lib\fenlight.py", line 6, in <module>
                                                       routing(sys)
                                                     File "C:\Users\ShlomiD\AppData\Roaming\Kodi\addons\plugin.video.fenlight\resources\lib\modules\router.py", line 23, in routing
                                                       return Sources().playback_prep(params)
                                                     File "C:\Users\ShlomiD\AppData\Roaming\Kodi\addons\plugin.video.fenlight\resources\lib\modules\sources.py", line 91, in playback_prep
                                                       else: return self.get_sources()
                                                     File "C:\Users\ShlomiD\AppData\Roaming\Kodi\addons\plugin.video.fenlight\resources\lib\modules\sources.py", line 118, in get_sources
                                                       results = self.process_results(self.orig_results)
                                                     File "C:\Users\ShlomiD\AppData\Roaming\Kodi\addons\plugin.video.fenlight\resources\lib\modules\sources.py", line 167, in process_results
                                                       for file_type in filter_keys: results = self._special_filter(results, file_type)
                                                     File "C:\Users\ShlomiD\AppData\Roaming\Kodi\addons\plugin.video.fenlight\resources\lib\modules\sources.py", line 433, in _special_filter
                                                       results = [i for i in results if all(x in i['extraInfo'] for x in (key, self.hdr_filter_key)) or not key in i['extraInfo']]
                                                     File "C:\Users\ShlomiD\AppData\Roaming\Kodi\addons\plugin.video.fenlight\resources\lib\modules\sources.py", line 433, in <listcomp>
                                                       results = [i for i in results if all(x in i['extraInfo'] for x in (key, self.hdr_filter_key)) or not key in i['extraInfo']]
                                                   AttributeError: 'Sources' object has no attribute 'hdr_filter_key'
                                                   -->End of Python script error report<--

**Comment by Tikipeter** [comment]
LOL. Yeah, still trying to sort it out. Had to get out of bed twice now and restart my computer. Hopefully version `1.0.80` will have everything fixed.

Serves me right for trying to do a little re-write of some of the filtering code nice and quick before an update because the mood took me. Fucking useless sometimes. :)
