### ISSUE TITLE
Fen Light / Fen - TRAKT Authorization Error

### ISSUE THREAD

**Issue by TwilightMercy** [Tikipeter/tikipeter.github.io#42]
Hi Dear Tikipeter,

Recently (from the last day I believe), TRAKT authorizations in Fen Light / Fen addons returns error in Kodi, and also in log:

```
 info <general>: ###Trakt Error###: 401 Client Error: Unauthorized for url: https://api.trakt.tv//users/me
 info <general>: ###Trakt Error###: 401 Client Error: Unauthorized for url: https://api.trakt.tv/sync/last_activities
error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                  - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                 Error Type: <class 'TypeError'>
                 Error Contents: 'NoneType' object is not subscriptable
                 Traceback (most recent call last):
                   File "addons\plugin.video.fenlight\resources\lib\fenlight.py", line 6, in <module>
                     routing(sys)
                   File "addons\plugin.video.fenlight\resources\lib\modules\router.py", line 35, in routing
                     return exec('trakt_api.%s(params)' % mode.split('.')[1])
                   File "<string>", line 1, in <module>
                   File "addons\plugin.video.fenlight\resources\lib\apis\trakt_api.py", line 164, in trakt_authenticate
                     trakt_sync_activities(force_update=True)
                   File "addons\plugin.video.fenlight\resources\lib\apis\trakt_api.py", line 731, in trakt_sync_activities
                     if not _compare(latest['all'], cached['all']): return 'not needed'
                 TypeError: 'NoneType' object is not subscriptable
                 -->End of Python script error report<--
```

I don't know if it's temporary issue from TRAKT API, or they changed something

Thank you for all the support!

**Comment by DIAMONDO98** [comment]
I was just about to submit the same thing, I get the same error as above.

**Comment by DIAMONDO98** [comment]
@TwilightMercy it seems to be working for me now? Can you confirm also? Seems like it was a Trakt issue. I checked their forums.

**Comment by TwilightMercy** [comment]
> @TwilightMercy it seems to be working for me now? Can you confirm also? Seems like it was a Trakt issue. I checked their forums.

Yes it works now,
btw Can you send link to the issue discussed in their forum?

**Comment by DIAMONDO98** [comment]
https://forums.trakt.tv/t/trakt-authorisation/19035/8

https://forums.trakt.tv/t/unable-to-activate/19030/14
